apiVersion: v1
kind: Service
metadata:
  namespace: {{ namespace }}
  name: libretranslate
  labels:
    app: libretranslate
spec:
  type: ClusterIP
  selector:
    app: libretranslate
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: web
