apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: {{ namespace }}
  name: libretranslate
spec:
  ingressClassName: traefik
  rules:
    - host: {{ server_host }}
      http:
        paths:
          - backend:
              service:
                name: libretranslate
                port:
                  number: 5000
            path: /
            pathType: Prefix
